# Generated by Django 3.1 on 2020-08-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddatabase', '0002_auto_20200826_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='brand_name',
            field=models.CharField(default=0, help_text='Brand name of the medication', max_length=200),
            preserve_default=False,
        ),
    ]
