# Generated by Django 3.1 on 2020-08-26 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meddatabase', '0004_auto_20200826_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='medinstance',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meddatabase.patient'),
        ),
    ]
