# Generated by Django 3.1 on 2020-08-26 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meddatabase', '0005_medinstance_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular prescription across whole database', primary_key=True, serialize=False),
        ),
    ]
