# Generated by Django 3.1 on 2020-08-26 05:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr_frequency', models.CharField(max_length=5)),
                ('long_frequency', models.CharField(help_text='Write out the frequency without abbreviations', max_length=200)),
            ],
            options={
                'ordering': ['abbr_frequency'],
            },
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a medication indication (ex: hypertension)', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('phonetic_name', models.CharField(help_text='Spell the medication name phonetically', max_length=200)),
                ('dose', models.CharField(max_length=10, verbose_name='Dose')),
                ('mechanism_of_action', models.TextField(help_text='Enter a brief description of the mechanism of action', max_length=1000)),
                ('indication', models.ManyToManyField(help_text='Select an indication for this medication', to='meddatabase.Indication')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr_route', models.CharField(help_text='Write the route in abbreviated form (ex: PO, SQ, etc.)', max_length=5)),
                ('long_route', models.CharField(help_text='Write the route in a patient-friendly form', max_length=100)),
            ],
            options={
                'ordering': ['abbr_route'],
            },
        ),
        migrations.CreateModel(
            name='MedInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('date_prescribed', models.DateField(blank=True, null=True)),
                ('date_filled', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Adherent'), ('u', 'Unsure'), ('n', 'Not Adherent'), ('o', 'Out of Medication')], default='m', help_text='Medication Status', max_length=1)),
                ('frequency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meddatabase.frequency')),
                ('med', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meddatabase.med')),
            ],
            options={
                'ordering': ['date_filled'],
            },
        ),
        migrations.AddField(
            model_name='med',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meddatabase.route'),
        ),
    ]
