# Generated by Django 3.1 on 2020-08-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='abbr_frequency',
            field=models.CharField(help_text='Write out the frequency in abbreviated form (e.g. QD, BID, TID, etc.)', max_length=5),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='long_frequency',
            field=models.CharField(help_text='Write out the frequency in a patient-friendly format all lowercase without abbreviations', max_length=200),
        ),
    ]
