# Generated by Django 3.1 on 2020-08-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meddatabase', '0007_medinstance_prescriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Med_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='Enter a medication class', max_length=100, verbose_name='Medication Class')),
                ('interactions', models.ManyToManyField(blank=True, help_text='Enter the classes this medication interacts with', null=True, to='meddatabase.Med_Class', verbose_name='Interactions')),
            ],
        ),
        migrations.AddField(
            model_name='med',
            name='med_class',
            field=models.ForeignKey(help_text='Enter the name of the medication class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meddatabase.med_class', verbose_name='Medication Class'),
        ),
    ]
