# Generated by Django 3.1 on 2021-04-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrec_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='med_pronun',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pronunciation'),
        ),
        migrations.AddField(
            model_name='medication',
            name='trade_name_regex',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
