# Generated by Django 3.1 on 2021-04-08 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medrec_v2', '0002_auto_20210407_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='trade_name_regex',
        ),
    ]
