# Generated by Django 3.1 on 2021-04-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrec_v2', '0005_auto_20210408_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siglookup',
            name='sig_plain_text',
            field=models.CharField(max_length=200),
        ),
    ]
