# Generated by Django 3.1 on 2021-04-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrec_v2', '0006_auto_20210408_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='siglookup',
            name='sig_bool',
            field=models.BooleanField(default=False, verbose_name='Regex Used'),
            preserve_default=False,
        ),
    ]
