# Generated by Django 3.2 on 2021-04-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medrec_v2', '0007_siglookup_sig_bool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siglookup',
            options={'ordering': ['sig_name']},
        ),
    ]
